name: Run Python Script

on:
  push:
    branches:
      - main # Triggers the workflow on pushes to the main branch

jobs:
  run-script:
    runs-on: ubuntu-latest # Specifies the operating system for the runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Checks out the repository content

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Specifies the Python version to use

    - name: Run Python script
      run: python test.py # Executes the test.py script
